const products = [
  {id:'p1',name:'Pupusas revueltas',category:'Plato fuerte',price:3.50,description:'Queso, frijol y chicharrón · 2 unidades',icon:'🫓',tone:''},
  {id:'p2',name:'Pupusas de queso',category:'Plato fuerte',price:2.50,description:'Quesillo derretido · 2 unidades',icon:'🫓',tone:'rose'},
  {id:'p3',name:'Tamal de elote',category:'Postre',price:2.50,description:'Tierno y recién preparado',icon:'🌽',tone:'green'},
  {id:'p4',name:'Horchata',category:'Bebida',price:1.25,description:'Bebida artesanal de la casa',icon:'🥛',tone:''},
  {id:'p5',name:'Tostada de plátano',category:'Postre',price:1.00,description:'Plátano dulce con crema',icon:'🍌',tone:'rose'},
  {id:'p6',name:'Ensalada fresca',category:'Bebida',price:1.50,description:'Refrescante bebida tradicional',icon:'🥤',tone:'green'},
  {id:'p7',name:'Yuca frita',category:'Extra',price:2.00,description:'Con curtido y salsa de tomate',icon:'🍟',tone:''},
  {id:'p8',name:'Empanadas',category:'Postre',price:2.00,description:'Rellenas de leche y canela',icon:'🥟',tone:'rose'}
];
const combos = [
  {id:'c1',name:'El Santaneco',price:15.00,description:'Una selección para disfrutar lo mejor de casa.',icon:'🍽️',tone:'green',category:'Combo'},
  {id:'c2',name:'Combo para las Madrecitas',price:16.00,description:'Un detalle especial para compartir en familia.',icon:'🌷',tone:'rose',category:'Combo'},
  {id:'c3',name:'De todo',price:11.00,description:'Sabores variados para una comida completa.',icon:'🥘',tone:'',category:'Combo'}
];
const sampleOrders = [
  {id:'ORD-104',customer:'Mesa 04',items:'El Santaneco × 1',total:15,status:'Procesada',time:'12:42'},
  {id:'ORD-103',customer:'Mesa 02',items:'Pupusas revueltas × 2',total:7,status:'Procesada',time:'12:28'},
  {id:'ORD-102',customer:'Para llevar',items:'Horchata × 2 · Tamal de elote × 1',total:5,status:'Pendiente',time:'12:17'},
  {id:'ORD-101',customer:'Mesa 01',items:'Combo De todo × 1',total:11,status:'Procesada',time:'11:56'}
];
const names={inicio:'Inicio',orden:'Nueva orden',ordenes:'Órdenes',productos:'Productos',combos:'Combos',usuarios:'Usuarios'};
const money=n=>'$'+Number(n).toFixed(2);
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('ra-demo-'+key))??fallback}catch{return fallback}};
const save=(key,value)=>localStorage.setItem('ra-demo-'+key,JSON.stringify(value));
let orders=load('orders',sampleOrders), userList=load('users',[{name:'Fernando José',username:'fernando',role:'Administrador',status:'Activo'},{name:'Cajero Demo',username:'cajero',role:'Cajero',status:'Activo'}]);
let cart={}, activeView='inicio', searchTerm='', categoryFilter='Todas', toastTimer;
const app=document.querySelector('#app');
document.querySelector('#today').textContent=new Intl.DateTimeFormat('es-SV',{weekday:'short',day:'numeric',month:'short'}).format(new Date());
function notify(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
function setView(view){activeView=view;searchTerm='';categoryFilter='Todas';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#crumb').textContent=names[view];render()}
function heading(kicker,title,subtitle,action=''){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function stat(label,value,note,icon,tone=''){return `<article class="stat-card"><span class="stat-icon ${tone}">${icon}</span><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></article>`}
function badge(status){const cls=status==='Pendiente'?'pending':status==='Anulada'?'cancel':'';return `<span class="status ${cls}">${status}</span>`}
function orderRows(list){if(!list.length)return `<tr><td colspan="5"><div class="empty-state"><span>▤</span><h3>Sin órdenes todavía</h3><p>Las nuevas órdenes aparecerán aquí.</p></div></td></tr>`;return list.map(o=>`<tr><td><strong>${o.id}</strong></td><td>${o.customer}</td><td>${o.time||'Ahora'}</td><td><strong>${money(o.total)}</strong></td><td>${badge(o.status)}</td></tr>`).join('')}
function tableOrders(list){return `<div class="table-wrap"><table><thead><tr><th>Orden</th><th>Cliente</th><th>Hora</th><th>Total</th><th>Estado</th></tr></thead><tbody>${orderRows(list)}</tbody></table></div>`}
function card(item){return `<article class="product-card"><div class="product-art ${item.tone}"><span class="category-chip">${item.category}</span>${item.icon}</div><div class="product-info"><div class="product-title">${item.name}</div><p>${item.description}</p><div class="product-bottom"><span class="price">${money(item.price)}</span><button class="add-btn" data-add="${item.id}" aria-label="Agregar ${item.name}">+</button></div></div></article>`}
function productCatalog(items,withFilters=true){const categories=['Todas',...new Set(items.map(i=>i.category))];let filtered=items.filter(i=>i.name.toLowerCase().includes(searchTerm.toLowerCase())&&(categoryFilter==='Todas'||i.category===categoryFilter));return `${withFilters?`<div class="toolbar"><label class="search"><input id="search" placeholder="Buscar ${activeView==='combos'?'combo':'producto'}..." value="${searchTerm}" aria-label="Buscar"></label><select class="filter-select" id="category" aria-label="Filtrar por categoría">${categories.map(c=>`<option ${c===categoryFilter?'selected':''}>${c}</option>`).join('')}</select></div>`:''}<div class="product-grid">${filtered.length?filtered.map(card).join(''):`<div class="empty-state"><span>⌕</span><h3>No encontramos resultados</h3><p>Prueba con otra búsqueda o categoría.</p></div>`}</div>`}
function cartRows(){const entries=Object.values(cart);if(!entries.length)return `<div class="cart-empty"><span>🧺</span>Agrega productos para empezar</div>`;return entries.map(({item,qty})=>`<div class="cart-row"><div><b>${item.name}</b><br><small>${money(item.price)} c/u · ${money(item.price*qty)}</small></div><div class="qty-controls"><button data-qty="${item.id}" data-delta="-1" aria-label="Quitar uno">−</button><span>${qty}</span><button data-qty="${item.id}" data-delta="1" aria-label="Agregar uno">+</button></div></div>`).join('')}
function cartTotal(){return Object.values(cart).reduce((sum,row)=>sum+row.item.price*row.qty,0)}
function orderPage(){const items=[...products,...combos];return `${heading('PUNTO DE VENTA','Nueva orden','Selecciona productos para armar una orden.',`<button class="btn secondary" data-clear-cart>↺ &nbsp;Limpiar</button>`)}<div class="notice">Demo interactiva: las órdenes se guardan solo en este navegador y usan datos de muestra.</div><div class="order-layout"><section>${productCatalog(items)}</section><aside class="panel order-panel"><div class="panel-head"><h2>Orden actual</h2><span class="status">${Object.values(cart).reduce((n,x)=>n+x.qty,0)} artículos</span></div><div id="cartRows">${cartRows()}</div><div class="field"><label for="customer">Nombre o mesa</label><input id="customer" placeholder="Ej. Mesa 05" value="${escapeHtml(document.querySelector('#customer')?.value||'')}"></div><div class="cart-total"><span>Total</span><b>${money(cartTotal())}</b></div><button class="btn" data-checkout ${Object.keys(cart).length?'':'disabled'}>✓ &nbsp;Procesar orden</button></aside></div>`}
function dashboard(){const todayTotal=orders.filter(o=>o.status!=='Anulada').reduce((sum,o)=>sum+o.total,0);const count=orders.filter(o=>o.status!=='Anulada').length;return `${heading('MIÉRCOLES · TU RESTAURANTE','Buenos días, Fernando 👋','Aquí tienes un vistazo de la actividad en tu punto de venta.',`<button class="btn" data-go="orden">＋ &nbsp;Nueva orden</button>`)}<div class="stats">${stat('Ventas de la demo',money(todayTotal),'Órdenes de ejemplo y de esta sesión','＄')}${stat('Órdenes registradas',count,'En este navegador','▤','orange')}${stat('Productos activos',products.length,'En el catálogo demo','◈')}${stat('Combos disponibles',combos.length,'Opciones para compartir','▦','orange')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>Órdenes recientes</h2><button class="text-link" data-go="ordenes">Ver todas →</button></div>${tableOrders(orders.slice(0,4))}</section><section class="panel"><div class="panel-head"><h2>Favoritos de la casa</h2><span class="eyebrow" style="margin:0">TOP PRODUCTOS</span></div><div class="popular-list">${[products[0],products[1],combos[0],products[3]].map(p=>`<div class="popular-item"><span class="food-icon">${p.icon}</span><span class="popular-name">${p.name}<small>${p.category}</small></span><span class="popular-price">${money(p.price)}</span></div>`).join('')}</div><div class="quick-actions"><button class="btn light" data-go="productos">Ver productos</button><button class="btn secondary" data-go="combos">Ver combos</button></div></section></div>`}
function ordersPage(){return `${heading('SEGUIMIENTO','Órdenes','Consulta los pedidos de muestra y los creados en esta demo.',`<button class="btn" data-go="orden">＋ &nbsp;Nueva orden</button>`)}<section class="panel"><div class="panel-head"><h2>Historial de órdenes</h2><span class="status">${orders.length} registros</span></div>${tableOrders(orders)}</section>`}
function catalogPage(isCombos){const list=isCombos?combos:products;return `${heading(isCombos?'OFERTAS DE LA CASA':'CATÁLOGO',' '+(isCombos?'Combos':'Productos'),isCombos?'Opciones listas para disfrutar y compartir.':'Productos disponibles en el punto de venta.',`<button class="btn" data-new="${isCombos?'combo':'producto'}">＋ &nbsp;Agregar ${isCombos?'combo':'producto'}</button>`)}${productCatalog(list)}</div>`}
function usersPage(){return `${heading('EQUIPO','Usuarios','Cuentas de ejemplo para representar los roles de la aplicación.',`<button class="btn" data-new="usuario">＋ &nbsp;Agregar usuario</button>`)}<div class="notice">Los usuarios son solo datos demostrativos. Esta versión web no incluye autenticación ni conexión a una base de datos.</div><section class="panel"><div class="panel-head"><h2>Equipo de trabajo</h2><span class="status">${userList.length} usuarios</span></div><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Estado</th></tr></thead><tbody>${userList.map(u=>`<tr><td><strong>${escapeHtml(u.name)}</strong></td><td>${escapeHtml(u.username)}</td><td>${escapeHtml(u.role)}</td><td>${badge(u.status)}</td></tr>`).join('')}</tbody></table></div></section>`}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){app.innerHTML=activeView==='inicio'?dashboard():activeView==='orden'?orderPage():activeView==='ordenes'?ordersPage():activeView==='productos'?catalogPage(false):activeView==='combos'?catalogPage(true):usersPage();}
function addToCart(id){const item=[...products,...combos].find(p=>p.id===id);if(!item)return;cart[id]??={item,qty:0};cart[id].qty++;notify(`${item.name} agregado a la orden`);render()}
function changeQty(id,delta){if(!cart[id])return;cart[id].qty+=delta;if(cart[id].qty<=0)delete cart[id];render()}
function showModal(type){const config={producto:['Nuevo producto','Agrega un producto de ejemplo al catálogo.','Nombre del producto','Precio'],combo:['Nuevo combo','Agrega un combo de ejemplo.','Nombre del combo','Precio'],usuario:['Nuevo usuario','Agrega un usuario de ejemplo al equipo.','Nombre completo','Usuario']};const [title,desc,label,second]=config[type];const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><h2>${title}</h2><p>${desc}</p><form id="newForm"><div class="field"><label for="first">${label}</label><input id="first" required maxlength="55" autofocus></div><div class="field"><label for="second">${second}</label><input id="second" ${type==='usuario'?'required':''} ${type==='usuario'?'maxlength="32"':'type="number" min="0.01" step="0.01"'}></div>${type==='producto'?`<div class="field"><label for="third">Categoría</label><select id="third"><option>Plato fuerte</option><option>Bebida</option><option>Postre</option><option>Extra</option></select></div>`:''}<div class="modal-actions"><button type="button" class="btn secondary" data-dismiss>Cancelar</button><button class="btn" type="submit">Guardar</button></div></form></section>`;document.body.append(modal);modal.querySelector('#first').focus();modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('[data-dismiss]'))modal.remove()});modal.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const first=modal.querySelector('#first').value.trim(),secondValue=modal.querySelector('#second').value.trim();if(type==='usuario'){userList.push({name:first,username:secondValue,role:'Cajero',status:'Activo'});save('users',userList)}else{const list=type==='producto'?products:combos;list.push({id:'custom-'+Date.now(),name:first,category:type==='producto'?modal.querySelector('#third').value:'Combo',price:Number(secondValue),description:'Agregado en esta demo local',icon:type==='producto'?'🍴':'🍱',tone:'green'})}modal.remove();render();notify(`${title.replace('Nuevo ','')} guardado en esta demo`)})}
app.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){setView(nav.dataset.view);return}const go=e.target.closest('[data-go]');if(go){setView(go.dataset.go);return}const add=e.target.closest('[data-add]');if(add){addToCart(add.dataset.add);return}const qty=e.target.closest('[data-qty]');if(qty){changeQty(qty.dataset.qty,Number(qty.dataset.delta));return}const fresh=e.target.closest('[data-new]');if(fresh){showModal(fresh.dataset.new);return}if(e.target.closest('[data-clear-cart]')){cart={};render();notify('Orden limpia');return}if(e.target.closest('[data-checkout]')){if(!Object.keys(cart).length)return;const customer=document.querySelector('#customer').value.trim()||'Para llevar';const now=new Date();orders.unshift({id:'ORD-'+String(Date.now()).slice(-5),customer,items:Object.values(cart).map(x=>`${x.item.name} × ${x.qty}`).join(' · '),total:cartTotal(),status:'Procesada',time:new Intl.DateTimeFormat('es-SV',{hour:'2-digit',minute:'2-digit'}).format(now)});save('orders',orders);cart={};setView('ordenes');notify('¡Orden procesada! Se guardó en este navegador.')}});
app.addEventListener('input',e=>{if(e.target.id==='search'){searchTerm=e.target.value;const pos=e.target.selectionStart;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos)}});
app.addEventListener('change',e=>{if(e.target.id==='category'){categoryFilter=e.target.value;render()}});
document.querySelector('#navigation').addEventListener('click',e=>{const btn=e.target.closest('[data-view]');if(btn)setView(btn.dataset.view)});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();setView('orden')}if(e.key==='Escape')document.querySelector('.modal-backdrop')?.remove()});
render();
